name: Test
on: [pull_request, push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: 'test-db'
          postgresql user: runner
      - run: npm ci
      - run: npm run test
        env:
          DATABASE_URL: 'postgresql://root:albino@localhost:5432/test-db'
