name: Test

on: [pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner1234
          POSTGRES_DB: 'poporopo-test'
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - run: npm ci
      - run: npm run test
        env:
          DB_USER: runner
          DB_PASS: runner1234

