name: Test

on: [pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
          sudo -u postgres createuser --superuser $USER
          sudo -u postgres createdb poporopo-test
      - run: npm ci
      - run: npm run test
