name: Test

on: [pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      # Change user name and password to meet your requirements
      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER runner PASSWORD NULL" --command="\du"
      # Change database name to meet your requirements
      - name: Create additional database
        run: |
          sudo -u postgres createdb --owner=runner poporopo-test

      - run: npm ci
      - run: npm run test
