name: Test

on: [pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready
      - name: Create Test User
        run: |
          sudo -u postgres createuser --superuser $USER
      - name: Create Test Database
        run: |
          sudo -u postgres createdb --owner=$USER poporopo-test
      - name: Attempt Connection
        run: |
          psql -U $USER -w -d poporopo-test -h localhost -c "SELECT version()"
      - run: npm ci
      - run: npm run test
